pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK17'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t techstore:latest .'
            }
        }

        stage('Stop Old Container') {
            steps {
                sh 'docker stop techstore || exit 0'
                sh 'docker rm techstore || exit 0'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d --name techstore -p 8081:8081 techstore:latest'
            }
        }
    }
}